spring:
  application:
    name: cloud-dubbo-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.102:8848

dubbo:
  scan:
    base-packages: com.ghy.clouddubboserver.service
  protocol:
    port: 8882
    name: dubbo
